server:
  port: 80
  servlet:
    context-path: /api
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/investree_sandboxing_01
    username: postgres
    password: root
security:
  jwt:
    enabled: true